{
 "title": "Kafka Dashboard",
 "description": "Example of an Kafka Dashboard for DC/OS 1.12",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory in Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (1m) by Topic",
   "type": "graph",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_messagesin_total[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (5m) by Topic",
   "type": "graph",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_messagesin_total[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka avg msg/sec (15m) by Topic",
   "type": "graph",
   "description": "Average messages per second per Kafka broker",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_messagesin_total[15m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Leaders per Broker",
   "type": "graph",
   "description": "Number of leaders on this broker. This should be mostly even across all brokers. If not, set auto.leader.rebalance.enable to true on all brokers in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kafka_server_replicamanager_leadercount)by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Count Across Brokers",
   "type": "graph",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_server_replicamanager_partitioncount)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "ActiveControllerCount",
   "type": "singlestat",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.\n\nIf this metric has a value greater than 1 it means that data is not being replicated to enough number of brokers thereby increasing the probability of data loss.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_cluster_partition_underreplicated)"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "ISR Expansion Rate",
   "type": "singlestat",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_isrexpands_total)"
    }
   ]
  },
  {
   "title": "ISR Shrink Rate",
   "type": "singlestat",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_isrshrinks_total)"
    }
   ]
  },
  {
   "title": "Producer Purgatory Requests Waiting",
   "type": "singlestat",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 49 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_produce)"
    }
   ]
  },
  {
   "title": "Delayed Fetch Operation Purgatory Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch)"
    }
   ]
  },
  {
   "title": "All Bytes In (1min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesin_total[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "All Bytes Out (1min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesout_total[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "All Bytes In (15min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesin_total[15m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "All Bytes Out (15min) per Broker",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesout_total[15m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Leaders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Max Recorded Leader Election Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 72 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_controller_controllerstats_leaderelectionrateandtimems)"
    }
   ]
  },
  {
   "title": "Unclean Leader Elections (15min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_controller_controllerstats_uncleanleaderelectionspersec)"
    }
   ]
  },
  {
   "title": "Max Lag - Follower/Leader Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 72 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_replicafetchermanager_maxlag)"
    }
   ]
  },
  {
   "title": "Avg Time Request Waits for Follower (ms)",
   "type": "singlestat",
   "description": "Time the request waits for the follower. This is non-zero for produce requests when acks=all",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 72 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\"})"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Current Request Queue Size",
   "type": "singlestat",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 75 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_network_requestchannel_requestqueuesize)"
    }
   ]
  },
  {
   "title": "Avg  Produce Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 75 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\"})"
    }
   ]
  },
  {
   "title": "Avg FetchConsumer Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 75 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_responsesendtimems{request=\"FetchConsumer\"})"
    }
   ]
  },
  {
   "title": "Avg Request Processing Time (ms) at Leader",
   "type": "singlestat",
   "description": "Time the request is processed at the leader",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 75 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_localtimems{request =~ \"Produce|FetchConsumer|FetchFollower\"})"
    }
   ]
  },
  {
   "title": "Avg Request Waiting Time in Request Queue (ms)",
   "type": "singlestat",
   "description": "Time the request waits in the request queue",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 75 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_requestqueuetimems{request =~ \"Produce|FetchConsumer|FetchFollower\"})"
    }
   ]
  },
  {
   "title": "Avg Request Waiting Time in Response Queue (ms)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 75 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_responsequeuetimems{request =~ \"Produce|FetchConsumer|FetchFollower\"})"
    }
   ]
  },
  {
   "title": "Produce Request Rate / sec (15min) by Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequests_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate / sec (15min) by Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequests_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate / sec (15min) by Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequests_total) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate / sec (15min) by Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequests_total) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "请求在请求队列等待时间",
   "type": "graph",
   "description": "请求(producer,Fetch-Consumer,Fetch-Follower)在请求队列中的等待时间",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestqueuetimems{request =~ \"Produce|FetchConsumer|FetchFollower\"}[5m])",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "graph",
   "description": "Average fraction of time the network processor threads are idle. Values are between 0 (all resources are used) and 1 (all resources are available)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_processor_idlepercent_networkprocessor_0) by (instance)",
     "legendFormat": "{{instance}}-networkprocessor_0"
    },
    {
     "expr": "avg(kafka_network_processor_idlepercent_networkprocessor_1) by (instance)",
     "legendFormat": "{{instance}}-networkprocessor_1"
    },
    {
     "expr": "avg(kafka_network_processor_idlepercent_networkprocessor_2) by (instance)",
     "legendFormat": "{{instance}}-networkprocessor_2"
    }
   ]
  },
  {
   "title": "请求在响应队列中等待的时间",
   "type": "graph",
   "description": "Time the request waits in the response queue",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_responsequeuetimems{request =~ \"Produce|FetchConsumer|FetchFollower\"}[5m])",
     "legendFormat": "{{instance}}{{request}}"
    }
   ]
  },
  {
   "title": "等待follower花费的时间",
   "type": "graph",
   "description": "请求(producer,Fetch-Consumer,Fetch-Follower)等待follower花费的时间",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_remotetimems{request =~ \"Produce|FetchConsumer|FetchFollower\"}[15m])",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "(producer,Fetch-Consumer,Fetch-Follower)请求耗费的所有时间",
   "type": "graph",
   "description": "一个请求(producer,Fetch-Consumer,Fetch-Follower)耗费的所有时间",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_totaltimems{request =~ \"Produce|FetchConsumer|FetchFollower\"}[5m])",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "leader处理请求花费的时间",
   "type": "graph",
   "description": "请求(producer,Fetch-Consumer,Fetch-Follower)在leader处理请求花的时间",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_localtimems{request =~ \"Produce|FetchConsumer|FetchFollower\"}[5m])",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "发送响应花费的时间",
   "type": "graph",
   "description": "Time to send the response",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_responsesendtimems{request =~ \"Produce|FetchConsumer|FetchFollower\"}[5m])",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  }
 ]
}