{
 "title": "prometheus_zookeeper",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": "label_values(zk_up{job=~\"(zk)\"}, project)"
   }
  ]
 },
 "panels": [
  {
   "title": "zookeeper服务是否可用（0:不可用;1:可用）",
   "type": "graph",
   "description": "zookeeper服务是否可用（0:不可用;1:可用）",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_up{job='zk',project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "节点选举情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_server_state{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}:{{state}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "description": "zk_num_alive_connections",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "watches的数量",
   "type": "graph",
   "description": "zk_watch_count watches的数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_watch_count{job='zk',project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "发送给客户端的包数量",
   "type": "graph",
   "description": "zk_packets_sent 发送给客户单的包数量，主要是响应和通知",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_sent{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "打开文件数量",
   "type": "graph",
   "description": "zk_open_file_descriptor_count 打开文件数量，当这个值大于允许值得85%时报警",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "节点数量",
   "type": "graph",
   "description": "zk_znode_count znodes的数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_znode_count{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "临时节点数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_ephemerals_count{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "数据大小",
   "type": "graph",
   "description": "zk_approximate_data_size 数据大小",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "排队请求的数量",
   "type": "graph",
   "description": "zk_outstanding_requests 排队请求的数量，当ZooKeeper超过了它的处理能力时，这个值会增大，建议设置报警阀值为10",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最大允许打开的文件数",
   "type": "graph",
   "description": "zk_max_file_descriptor_count 最大允许打开的文件数，由ulimit控制",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_max_file_descriptor_count{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "接收到客户端请求的包数量",
   "type": "graph",
   "description": "zk_packets_received 接收到客户端请求的包数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_received{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "接收到客户端请求的包数量",
   "type": "graph",
   "description": "zk_packets_received 接收到客户端请求的包数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_received{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最高延迟",
   "type": "graph",
   "description": "最高延迟",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_max_latency{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最低延迟",
   "type": "graph",
   "description": "最低延迟",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_min_latency{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "平均延迟",
   "type": "graph",
   "description": "平均延迟",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{job=\"zk\",project=\"$project\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}